-- MySQL Script generated by MySQL Workbench
-- Sun May 14 08:02:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ics199grp00
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ics199grp00
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ics199grp00` DEFAULT CHARACTER SET utf8 ;
USE `ics199grp00` ;

-- -----------------------------------------------------
-- Table `ics199grp00`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ics199grp00`.`categories` ;

CREATE TABLE IF NOT EXISTS `ics199grp00`.`categories` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ics199grp00`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ics199grp00`.`customer` ;

CREATE TABLE IF NOT EXISTS `ics199grp00`.`customer` (
  `cust_id` INT NOT NULL DEFAULT 1,
  `f_name` VARCHAR(45) NOT NULL,
  `l_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cust_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ics199grp00`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ics199grp00`.`products` ;

CREATE TABLE IF NOT EXISTS `ics199grp00`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_description` MEDIUMTEXT NULL DEFAULT NULL,
  `product_price` DECIMAL(9,2) NOT NULL,
  `product_image` VARCHAR(255) NULL DEFAULT NULL,
  `categories_cat_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_products_categories1_idx` (`categories_cat_id` ASC),
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`categories_cat_id`)
    REFERENCES `ics199grp00`.`categories` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ics199grp00`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ics199grp00`.`cart` ;

CREATE TABLE IF NOT EXISTS `ics199grp00`.`cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL DEFAULT 1,
  `products_product_id` INT NOT NULL,
  `time` DATETIME NOT NULL,
  `customer_cust_id` INT NULL,
  PRIMARY KEY (`cart_id`),
  INDEX `fk_cart_products1_idx` (`products_product_id` ASC),
  INDEX `fk_cart_customer1_idx` (`customer_cust_id` ASC),
  CONSTRAINT `fk_cart_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `ics199grp00`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_customer1`
    FOREIGN KEY (`customer_cust_id`)
    REFERENCES `ics199grp00`.`customer` (`cust_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
