-- MySQL Script generated by MySQL Workbench
-- 04/20/17 15:45:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ICS199TemplateDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ICS199TemplateDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ICS199TemplateDB` DEFAULT CHARACTER SET utf8 ;
USE `ICS199TemplateDB` ;

-- -----------------------------------------------------
-- Table `ICS199TemplateDB`.`tblNames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICS199TemplateDB`.`tblNames` ;

CREATE TABLE IF NOT EXISTS `ICS199TemplateDB`.`tblNames` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
